sudo: true
dist: trusty
language: php

notifications:
  email: never

php:
  - 7.2
  - 7.1
  - 7.0

install:
  - composer install --prefer-dist

before_script:
  - sudo mkdir -p "/etc/php/${TRAVIS_PHP_VERSION}/mods-available"

script:
  - ./vendor/bin/phpunit
  - shellcheck bin/*.sh
