language: php

php:
  - 7.4snapshot
  - 7.3
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot

install:
  - composer install --prefer-dist --no-interactive

before_script:
  - sudo mkdir -p "/etc/php/${TRAVIS_PHP_VERSION}/mods-available"

script:
  - ./vendor/bin/phpunit
  - shellcheck bin/*.sh
