name: Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  coding-standards:
    name: Coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './bin'

  test-installation-runkit7:
    name: Test installation of runkit7
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, 7.4]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - name: Configure PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: pecl

    - name: Create PEAR cache directory
      run: |
        sudo mkdir -p /tmp/pear/{cache,download,temp}
        sudo chmod -R 777 /tmp/pear
        pecl update-channels

    - name: Run the installation script
      run: sudo sh bin/install-runkit.sh

    - name: Verify that runkit7 has been installed and activated
      run: php -m | grep runkit

  test-installation-runkit:
    name: Test installation of runkit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [5.6]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - name: Configure PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: pecl

    - name: Create PEAR cache directory
      run: |
        sudo mkdir -p /tmp/pear/{cache,download,temp}
        sudo chmod -R 777 /tmp/pear
        pecl update-channels

    - name: Run the installation script
      run: sudo sh bin/install-runkit.sh

    - name: Verify that runkit has been installed and activated
      run: php -m | grep runkit

